#!/bin/bash

type=$1

case $type in
    time)
        arg=%e
        ;;
    memory)
        arg=%M
        ;;
    *)
        echo "Unknown type $type"
        exit 1
        ;;
esac

outfile=graph-$type.txt
echo -n > $outfile
echo -n "depth" >> $outfile
for lang in `find * -type d`
do
    echo -ne "\t" >> $outfile
    echo -n $lang >> $outfile
done
echo >> $outfile

for depth in {1..9}
do
    echo -n $depth >> $outfile
    for lang in $(find * -type d)
    do
        echo -ne "\t" >> $outfile
        result=$(TIME=$arg time $lang/run $depth 2>&1 >/dev/null)
        if echo $result | grep -q 'Command exited'
        then
            echo -n '-' >> $outfile
        else
            echo -n $result >> $outfile
        fi
    done
    echo >> $outfile
done
