#!/usr/bin/env python

from pprint import pprint
import string
import sys

items = string.lowercase

rnd_state = 3

def myrandom():
    global rnd_state
    rnd_state = (rnd_state + 1) % 1001
    return rnd_state

def item():
    return items[myrandom() % len(items)]

def width():
    return myrandom() % 8 + 1

def generate(depth):
    if depth == 0:
        return item()
    else:
        result = {}
        for i in range(0, width()):
            it = item()
            result[it] = generate(depth - 1)
        return result

def count(tree):
    accum = {it: 0 for it in items}
    def count_accum(tree):
        if type(tree) is str:
            accum[tree] += 1
        else:
            for k, v in tree.items():
                accum[k] += 1
                count_accum(v)
    count_accum(tree)
    return accum

depth = int(sys.argv[1])
tree = generate(depth)
if depth < 4:
    pprint(tree)
counts = count(tree)
pprint(counts)
